 # ETL Notebook - Warehouse supply chain analytics
 this notebook handles the Extract, Transform and Load process.

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Load Raw Dataset
we load the raw dataco supply chain dataset from the data/raw directory.

In [6]:
df = pd.read_csv("../data/raw/DataCoSupplyChainDataset.csv", encoding="ISO-8859-1", engine="python")
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

## Initial Dataset Overview
before cleaning we inspect the dataset structure, column types and missing values.

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  str
 9   Customer City                  180519 non-null  str
 10  Customer Country               180519 non-null  str
 11  Customer Email                 180519 non-null  str
 12  Customer Fname                 180519 non-null  str
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  str
 15  Customer Password              180519 non-null  str
 16  Customer Segment               180519 non-null  str
 17  Customer State                 180519 non-null  str
 18  Customer Street                180519 non-null  str
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  str
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  str
 25  Order City                     180519 non-null  str
 26  Order Country                  180519 non-null  str
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  str
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  str
 41  Order State                    180519 non-null  str
 42  Order Status                   180519 non-null  str
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  str
 48  Product Name                   180519 non-null  str
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  str
 52  Shipping Mode                  180519 non-null  str
dtypes: float64(15), int64(14), str(24)
memory usage: 73.0 MB

## basic dataset summary
after inspecting the dataset structure with "df.info()", the next step is to generate descriptive stastitics using "df.describe()", and check for missing values using "df.isnull().sum()".
this helps understand the datasets scale, numeric ranges and any gaps before cleaning.

In [8]:
df.describe()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Price,Product Status
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180516.000000,180519.000000,180519.000000,...,180519.000000,180519.000000,180519.000000,180519.000000,24840.000000,180519.000000,180519.000000,0.0,180519.000000,180519.0
mean,3.497654,2.931847,21.974989,183.107609,0.548291,31.851451,6691.379495,35921.126914,5.443460,29.719955,...,2.127638,203.772096,183.107609,21.974989,55426.132327,692.509764,31.851451,NaN,141.232550,0.0
std,1.623722,1.374449,104.433526,120.043670,0.497664,15.640064,4162.918106,37542.461122,1.629246,9.813646,...,1.453451,132.273077,120.043670,104.433526,31919.279101,336.446807,15.640064,NaN,139.732492,0.0
min,0.000000,0.000000,-4274.979980,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,-33.937553,...,1.000000,9.990000,7.490000,-4274.979980,1040.000000,19.000000,2.000000,NaN,9.990000,0.0
25%,2.000000,2.000000,7.000000,104.379997,0.000000,18.000000,3258.500000,725.000000,4.000000,18.265432,...,1.000000,119.980003,104.379997,7.000000,23464.000000,403.000000,18.000000,NaN,50.000000,0.0
50%,3.000000,4.000000,31.520000,163.990005,1.000000,29.000000,6457.000000,19380.000000,5.000000,33.144863,...,1.000000,199.919998,163.990005,31.520000,59405.000000,627.000000,29.000000,NaN,59.990002,0.0
75%,5.000000,4.000000,64.800003,247.399994,1.000000,45.000000,9779.000000,78207.000000,7.000000,39.279617,...,3.000000,299.950012,247.399994,64.800003,90008.000000,1004.000000,45.000000,NaN,199.990005,0.0
max,6.000000,4.000000,911.799988,1939.989990,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,...,5.000000,1999.989990,1939.989990,911.799988,99301.000000,1363.000000,76.000000,NaN,1999.989990,0.0

In [9]:
df.isnull().sum()

Type                                  0
Days for shipping (real)              0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Fname                        0
Customer Id                           0
Customer Lname                        8
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Customer Zipcode                      3
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Order Country                         0
Order Customer Id                     0
order date (DateOrders)               0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Profit Per Order                0
Order Region                          0
Order State                           0
Order Status                          0
Order Zipcode                    155679
Product Card Id                       0
Product Category Id                   0
Product Description              180519
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64

## Missing values summary
this dataset contains vert few missing values:
- 'Customer_lname': 8 missing values
- 'Customer_zipcode': 3 missing values
all other columns are fully populated.
since the number of missing values is extremely small compared to the dataset size(180k rows) these can be handles without impacting the analysis.

## Cleaning column names
Column names contain spaces, capital letters and special characters. we standardise them to make analysis easier and ensure consistency.

In [10]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("(", "")
    .str.replace(")", "")
)
df.head()

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,...,order_zipcode,product_card_id,product_category_id,product_description,product_image,product_name,product_price,product_status,shipping_date_dateorders,shipping_mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

## Convert Date columns
several date-related columns are stored as strings, we convert them to datetime objects for more accurate time-based analysis.

In [16]:
date_cols = [
    'order_date_dateorders',
    'shipping_date_dateorders',
]

for col in date_cols:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], errors='coerce')

        df[date_cols].head()

## Handle missing values
now we handle the missing values in the dataset.

In [21]:
df.loc[:, 'customer_lname'] = df['customer_lname'].fillna('Unknown')
df.loc[:, 'customer_zipcode'] = df['customer_zipcode'].fillna(0)

df.isnull().sum().sort_values(ascending=False).head(10)

product_description            180519
order_zipcode                  155679
days_for_shipment_scheduled         0
days_for_shipping_real              0
type                                0
delivery_status                     0
late_delivery_risk                  0
category_id                         0
category_name                       0
customer_city                       0
dtype: int64

## Feature engineering
we create new columns from existing data to support later analysis.
these engineered features help us understand shipping performance, customer behaviour, and order patterns.

Features created:
-shipping_delay: real minus scheduled shipping days
-order_month: month extracted from order date
-order_weekday: weekday name of the shipping date
-shipping_weekday: weekday name of the shipping date
-high_value_order: flag for orders above the median order_item_total
-customer_full_name: combined first and last name

In [22]:
df['shipping_delay'] = (df['days_for_shipping_real'] - df['days_for_shipment_scheduled'])

df['order_month'] = df['order_date_dateorders'].dt.month

df['order_weekday'] = df['order_date_dateorders'].dt.day_name()

df['shipping_weekday'] = df['shipping_date_dateorders'].dt.day_name()

df['high_value_order'] = df['order_item_total'] > df['order_item_total'].median()

df['customer_full_name'] = df['customer_fname'] + ' ' + df['customer_lname']

## Verify Feature Engineering
We check that all engineered columns were created correctly and contain valid values.
This helps confirm the ETL steps worked as expected before saving the cleaned dataset.

In [24]:
df.columns

df[['shipping_delay',
    'order_month',
    'order_weekday',
    'shipping_weekday',
    'high_value_order',
    'customer_full_name']].head()

,shipping_delay,order_month,order_weekday,shipping_weekday,high_value_order,customer_full_name
0,-1,1,Wednesday,Saturday,True,Cally Holloway
1,1,1,Saturday,Thursday,True,Irene Luna
2,0,1,Saturday,Wednesday,True,Gillian Maldonado
3,-1,1,Saturday,Tuesday,True,Tana Tate
4,-2,1,Saturday,Monday,True,Orli Hendricks

## Save cleaned dataset
we save the cleaned and feature-engineered dataset into the cleaned folder, this will be used in the EDA notebook for further analysis.

In [25]:
df.to_csv("../data/cleaned/dataco_cleaned.csv", index=False)

## Automated ETL Pipeline
we create a ETL pipeline into a reusable function so the cleaning process can be repeated easily.

In [26]:
def etl_pipeline():
    df = pd.read_csv("../data/raw/DataCoSupplyChainDataset.csv", encoding="ISO-8859-1", engine="python")
#clean column names
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
        .str.replace("(", "")
        .str.replace(")", "")
    )
#convert date columns to datetime
    date_cols = [
        'order_date_dateorders',
        'shipping_date_dateorders',
    ]
    for col in date_cols:
        df[col] = pd.to_datetime(df[col], errors='coerce')

# handle missing values
    df.loc[:, 'customer_lname'] = df['customer_lname'].fillna('Unknown')
    df.loc[:, 'customer_zipcode'] = df['customer_zipcode'].fillna(0)

# create new features
    df['shipping_delay'] = (df['days_for_shipping_real'] - df['days_for_shipment_scheduled'])
    df['order_month'] = df['order_date_dateorders'].dt.month
    df['order_weekday'] = df['order_date_dateorders'].dt.day_name()
    df['shipping_weekday'] = df['shipping_date_dateorders'].dt.day_name()
    df['high_value_order'] = df['order_item_total'] > df['order_item_total'].median()
    df['customer_full_name'] = df['customer_fname'] + ' ' + df['customer_lname']

# save cleaned data to csv
    df.to_csv("../data/cleaned/dataco_cleaned.csv", index=False)

    return df

In [27]:
etl_df = etl_pipeline()
etl_df.head(10)

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,...,product_price,product_status,shipping_date_dateorders,shipping_mode,shipping_delay,order_month,order_weekday,shipping_weekday,high_value_order,customer_full_name
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,327.75,0,2018-02-03 22:56:00,Standard Class,-1,1,Wednesday,Saturday,True,Cally Holloway
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,327.75,0,2018-01-18 12:27:00,Standard Class,1,1,Saturday,Thursday,True,Irene Luna
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,327.75,0,2018-01-17 12:06:00,Standard Class,0,1,Saturday,Wednesday,True,Gillian Maldonado
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,327.75,0,2018-01-16 11:45:00,Standard Class,-1,1,Saturday,Tuesday,True,Tana Tate
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,327.75,0,2018-01-15 11:24:00,Standard Class,-2,1,Saturday,Monday,True,Orli Hendricks
5,TRANSFER,6,4,18.580000,294.980011,Shipping canceled,0,73,Sporting Goods,Tonawanda,...,327.75,0,2018-01-19 11:03:00,Standard Class,2,1,Saturday,Friday,True,Kimberly Flowers
6,DEBIT,2,1,95.180000,288.420013,Late delivery,1,73,Sporting Goods,Caguas,...,327.75,0,2018-01-15 10:42:00,First Class,1,1,Saturday,Monday,True,Constance Terrell
7,TRANSFER,2,1,68.430000,285.140015,Late delivery,1,73,Sporting Goods,Miami,...,327.75,0,2018-01-15 10:21:00,First Class,1,1,Saturday,Monday,True,Erica Stevens
8,CASH,3,2,133.720001,278.589996,Late delivery,1,73,Sporting Goods,Caguas,...,327.75,0,2018-01-16 10:00:00,Second Class,1,1,Saturday,Tuesday,True,Nichole Olsen
9,CASH,2,1,132.149994,275.309998,Late delivery,1,73,Sporting Goods,San Ramon,...,327.75,0,2018-01-15 09:39:00,First Class,1,1,Saturday,Monday,True,Oprah Delacruz